// 🍬 GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by Go Router Sugar - The Simplest Flutter Routing Ever!
//
// 🎯 This file provides a complete routing solution with:
//   ✅ Type-safe navigation
//   ✅ Zero string-based routing
//   ✅ Full parameter validation
//   ✅ Beautiful IntelliSense support
//
// 📖 Usage:
//   Navigate.toHome();
//   Navigate.toProduct(id: "123", category: "electronics");
//   context.goToHome();
//   context.goToProduct(id: "123");
//
// 🚀 Say goodbye to: context.go("/products/123?category=electronics")
// 🎉 Say hello to:   Navigate.toProduct(id: "123", category: "electronics")

import 'package:flutter/material.dart';
import 'package:go_router_sugar/go_router_sugar.dart';

import 'pages/about_page.dart';
import 'pages/faq_page.dart';
import 'pages/forgot_password_page.dart';
import 'pages/index_page.dart';
import 'pages/login_page.dart';
import 'pages/register_page.dart';

/// 🍬 Your App's Complete Routing Configuration
///
/// Generated from your page files with zero configuration required.
/// Just add this to your MaterialApp.router(routerConfig: AppRouter.router)
class AppRouter {
  AppRouter._(); // Private constructor - use static router instance

  /// 🎯 The complete GoRouter configuration for your app
  ///
  /// Includes 6 routes with full type safety and parameter validation.
  static final GoRouter router = GoRouter(
    initialLocation: '/',
    routes: [
      GoRoute(
        path: '/',
        builder: (context, state) {
          return const HomePage();
        },
      ),
      GoRoute(
        path: '/about',
        builder: (context, state) {
          return const AboutPage();
        },
      ),
      GoRoute(
        path: '/faq',
        builder: (context, state) {
          return const FaqPage();
        },
      ),
      GoRoute(
        path: '/forgot_password',
        builder: (context, state) {
          return const ForgotPasswordPage();
        },
      ),
      GoRoute(
        path: '/login',
        builder: (context, state) {
          return const LoginPage();
        },
      ),
      GoRoute(
        path: '/register',
        builder: (context, state) {
          return const RegisterPage();
        },
      ),
    ],
  );
}

/// 🗂️ Route Path Constants
///
/// Use these constants instead of hardcoded strings.
/// Example: context.go(Routes.home) instead of context.go("/home")
class Routes {
  Routes._(); // Private constructor

  /// 🏠 Home page - Your app's starting point
  static const String home = '/';

  /// 📄 About page
  static const String about = '/about';

  /// 📄 Faq page
  static const String faq = '/faq';

  /// 📄 ForgotPassword page
  static const String forgot_password = '/forgot_password';

  /// 📄 Login page
  static const String login = '/login';

  /// 📄 Register page
  static const String register = '/register';

  /// 📋 All available routes in your app
  static const List<String> all = [
    home,
    about,
    faq,
    forgot_password,
    login,
    register,
  ];
}

/// 🚀 Type-Safe Navigation API
///
/// Navigate to any page with full type safety and parameter validation.
/// No more string-based routing or runtime errors!
///
/// Example:
///   Navigate.toHome();
///   Navigate.toProduct(id: "123", category: "electronics");
class Navigate {
  Navigate._(); // Private constructor

  /// 🧭 The global navigator key for programmatic navigation
  static final GlobalKey<NavigatorState> _navigatorKey = GlobalKey<NavigatorState>();

  /// Access to the navigator key (for advanced use cases)
  static GlobalKey<NavigatorState> get navigatorKey => _navigatorKey;

  /// 🏠 Home page - Your app's starting point
  static void toHome() {
    final context = _navigatorKey.currentContext;
    if (context == null) {
      throw StateError('Navigator context is null. Make sure AppRouter.router is used in MaterialApp.router');
    }
    context.go('/');
  }

  /// 📄 About page
  static void toAbout() {
    final context = _navigatorKey.currentContext;
    if (context == null) {
      throw StateError('Navigator context is null. Make sure AppRouter.router is used in MaterialApp.router');
    }
    context.go('/about');
  }

  /// 📄 Faq page
  static void toFaq() {
    final context = _navigatorKey.currentContext;
    if (context == null) {
      throw StateError('Navigator context is null. Make sure AppRouter.router is used in MaterialApp.router');
    }
    context.go('/faq');
  }

  /// 📄 ForgotPassword page
  static void toForgot_password() {
    final context = _navigatorKey.currentContext;
    if (context == null) {
      throw StateError('Navigator context is null. Make sure AppRouter.router is used in MaterialApp.router');
    }
    context.go('/forgot_password');
  }

  /// 📄 Login page
  static void toLogin() {
    final context = _navigatorKey.currentContext;
    if (context == null) {
      throw StateError('Navigator context is null. Make sure AppRouter.router is used in MaterialApp.router');
    }
    context.go('/login');
  }

  /// 📄 Register page
  static void toRegister() {
    final context = _navigatorKey.currentContext;
    if (context == null) {
      throw StateError('Navigator context is null. Make sure AppRouter.router is used in MaterialApp.router');
    }
    context.go('/register');
  }

}

/// 🎯 BuildContext Extensions for Fluent Navigation
///
/// Use these extension methods for more idiomatic Flutter navigation.
/// Example: context.goToHome() instead of Navigate.toHome()
extension GoRouterSugarNavigation on BuildContext {

  /// 🏠 Home page - Your app's starting point
  void goToHome() => Navigate.toHome();

  /// 📄 About page
  void goToAbout() => Navigate.toAbout();

  /// 📄 Faq page
  void goToFaq() => Navigate.toFaq();

  /// 📄 ForgotPassword page
  void goToForgot_password() => Navigate.toForgot_password();

  /// 📄 Login page
  void goToLogin() => Navigate.toLogin();

  /// 📄 Register page
  void goToRegister() => Navigate.toRegister();

}
